on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: [windows-2022]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.10'
